# name: Deploy
# description: This workflow deploys the website to Vercel.

# env:
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     environment: production

#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install Vercel CLI
#         run: npm install --global vercel@latest

#       - name: Pull Vercel Environment Information
#         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Build Project Artifacts
#         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Deploy Project Artifacts to Vercel
#         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
